/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.lyne.proto;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface PrdInfo {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"PrdInfo\",\"namespace\":\"com.lyne.proto\",\"types\":[{\"type\":\"record\",\"name\":\"PrdIdentity\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"type\",\"type\":\"string\"}]},{\"type\":\"record\",\"name\":\"PrdInfoType\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"price\",\"type\":\"double\"}]}],\"messages\":{\"queryPrdInfo\":{\"request\":[{\"name\":\"requestType\",\"type\":\"PrdIdentity\"}],\"response\":\"PrdInfoType\"}}}");
  /**
   */
  com.lyne.proto.PrdInfoType queryPrdInfo(com.lyne.proto.PrdIdentity requestType) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends PrdInfo {
    public static final org.apache.avro.Protocol PROTOCOL = com.lyne.proto.PrdInfo.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void queryPrdInfo(com.lyne.proto.PrdIdentity requestType, org.apache.avro.ipc.Callback<com.lyne.proto.PrdInfoType> callback) throws java.io.IOException;
  }
}